<?php
// Datos de las fichas de producto (/windows/{estilo}/{serie}/ y /doors/{estilo}/{serie}/).
// Fuente provisional: fichas publicadas en premiumwindows.com/products/ (revisado 2026-10-03).
// PENDIENTE: confirmar con la matriz de producto oficial del cliente.
// Las imágenes son rutas de uploads; los PDFs se importan a la Media Library con
// `wp pwd import-product-docs` (inc/product-import.php) y se listan por serie + estilo.

// Clave: ruta de la página. 'legacy' es la URL del sitio actual (redirección 301).
function pwd_product_data() {
  return array(
    'windows/picture-windows/zenith' => array(
      'name' => 'Zenith Picture Window',
      'series' => 'zenith',
      'style' => 'picture',
      'legacy' => '/products/picture-windows/zenith-picture-window/',
      'lead' => 'Picture windows are the perfect fixed stress-free solution to enjoy your dream view with maximum sealing for energy efficiency.',
      'views' => array(
        array('Standard', '2024/10/PRM_Web-Zenith-Hero_0000_ZE_UNIT-PW.png'),
        array('Blinds outside', '2024/10/PRM_Web-Zenith-Hero_0001_ZE_UNIT-PW-ODL.png'),
        array('Blinds inside', '2024/10/PRM_Web-Zenith-Hero_0003_ZE_UNIT-PW-ODL-IN.png'),
        array('Operator', '2024/10/PRM_Web-Zenith-Hero_0002_ZE_UNIT-PW-ODL-IN-IG.png'),
      ),
      'highlights' => array('Elevated Luxury Experience', 'Cutting-Edge Performance Vinyl', 'Versatile Style Integration'),
      'material' => 'Performance Vinyl',
      'exterior' => array('Black'),
      'interior' => array('Black'),
      'blinds' => true,
      'benefits' => array(
        'title' => 'Performance Vinyl Benefits',
        'text' => 'Our innovative formula and performance co-extruded frames maintain the perfect balance between your desired luxury look and durability in the hottest of climates.',
        'items' => array('200°F Heat Resistance', 'Anti-Warping', 'Anti-Shrinking', 'Color-Fade Resistance'),
      ),
      'features' => array('Capstock Protection', 'Weather Sealed Bead'),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Streamlined Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/2″',
      'frame_options' => array('Retrofit 2-1/2″', 'Nail-On 1″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2024/10/ZeDeet-PW-BL-TRP.jpg',
        'Nail-On' => '2024/10/ZeDeet-PW-NO1-TRP.jpg',
        'Retrofit' => '2024/10/ZeDeet-PW-BL-TRP.jpg',
      ),
      'grids' => array(
        array('name' => 'Flat Grid 3/4″', 'image' => '2025/06/FlatGrid-3_4-Black.jpg', 'colors' => array('Black')),
        array('name' => 'Flat Grid 5/8″', 'image' => '2025/06/FlatGrid-5_8-Black.jpg', 'colors' => array('Black')),
        array('name' => 'Sculpted Grid 1″', 'image' => '2025/06/SculptedGrid-1-Black.jpg', 'colors' => array('Black')),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/picture-windows/timeless' => array(
      'name' => 'Timeless Picture Window',
      'series' => 'timeless',
      'style' => 'picture',
      'legacy' => '/products/picture-windows/timeless-series-picture-window/',
      'lead' => 'Picture windows are the perfect fixed stress-free solution to enjoy your dream view with maximum sealing for energy efficiency.',
      'views' => array(array('', '2025/12/PRM_Web-Timeless-Hero_0005_TI_UNIT-PW.png')),
      'highlights' => array('Premium Durability', 'Narrow Frames', 'Maximized Value'),
      'material' => 'Vinyl',
      'exterior' => array('White', 'Almond', 'Black Laminated'),
      'interior' => array('White', 'Almond'),
      'blinds' => false,
      'features' => array('Standard Glazing Bead'),
      'glazing' => array('Dual Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/4″ • 2-3/4″ (Nail-On 1″ & Block)',
      'frame_options' => array('Retrofit 1-3/4″', 'Retrofit 2-1/2″', 'Nail-On 1″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2025/10/14_TimeDeet-PW-BK.jpg',
        'Nail-On' => '2025/10/12_TimeDeet-PW-N13.jpg',
        'Retrofit' => '2025/10/10_TimeDeet-PW-R2.jpg',
      ),
      'grids' => array(
        array(
          'name' => 'Flat Grid 3/4″',
          'image' => '2025/06/FlatGrid-3_4-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
        array(
          'name' => 'Flat Grid 5/8″',
          'image' => '2025/06/FlatGrid-5_8-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
        array(
          'name' => 'Sculpted Grid 1″',
          'image' => '2025/06/SculptedGrid-1-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/picture-windows/serene' => array(
      'name' => 'Serene Picture Window',
      'series' => 'serene',
      'style' => 'picture',
      'legacy' => '/products/picture-windows/serene-series-picture-window/',
      'lead' => 'Picture windows are the perfect fixed stress-free solution to enjoy your dream view with maximum sealing for energy efficiency.',
      'views' => array(array('', '2022/03/SereneW-Picture_Vert-3D_TURNTABLE-RETROFIT-0001.png')),
      'highlights' => array('Sound Reduction', 'Energy Efficiency', 'Even Sightlines', 'Design Versatility'),
      'material' => 'Vinyl',
      'exterior' => array('White'),
      'interior' => array('White'),
      'blinds' => true,
      'features' => array('Even Sightlines', 'Standard Glazing Bead'),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/2″',
      'frame_options' => array('Retrofit 1-3/4″', 'Nail-On 1″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2022/03/Frame_detail-Block.jpg',
        'Nail-On' => '2022/03/Frame_detail-Nailon.jpg',
        'Retrofit' => '2022/03/Frame_detail-Retrofit.jpg',
      ),
      'grids' => array(
        array('name' => 'Flat Grid 3/4″', 'image' => '2025/06/FlatGrid-3_4-White.jpg', 'colors' => array('White')),
        array('name' => 'Flat Grid 5/8″', 'image' => '2025/06/FlatGrid-5_8-White.jpg', 'colors' => array('White')),
        array('name' => 'Sculpted Grid 1″', 'image' => '2025/06/SculptedGrid-1-White.jpg', 'colors' => array('White')),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/picture-windows/elegance' => array(
      'name' => 'Elegance Picture Window',
      'series' => 'elegance',
      'style' => 'picture',
      'legacy' => '/products/picture-windows/infinite-series-picture-window/',
      'lead' => 'Picture windows are the perfect fixed stress-free solution to enjoy your dream view with maximum sealing for energy efficiency.',
      'views' => array(array('', '2025/12/PRM_Web-Elegance-Hero_0001_EL_UNIT-PW.png')),
      'highlights' => array('Classic Styling', 'Even SightLines', 'Premium Durability'),
      'material' => 'Vinyl',
      'exterior' => array('White'),
      'interior' => array('White'),
      'blinds' => false,
      'features' => array('Standard Glazing Bead'),
      'glazing' => array('Dual Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '2-3/4″',
      'frame_options' => array('Retrofit 1-3/4″', 'Nail-On 1″', 'Block'),
      'frame_details' => array(
        'Block' => '2020/03/Elegance-Framing-Detail-Diagram_0002_ElegDeet-PW-BK.jpg',
        'Nail-On' => '2020/03/Elegance-Framing-Detail-Diagram_0001_ElegDeet-PW-N1.jpg',
        'Retrofit' => '2020/03/Elegance-Framing-Detail-Diagram_0000_ElegDeet-PW-R1.jpg',
      ),
      'grids' => array(
        array('name' => 'Flat Grid 3/4″', 'image' => '2025/06/FlatGrid-3_4-White.jpg', 'colors' => array('White')),
        array('name' => 'Flat Grid 5/8″', 'image' => '2025/06/FlatGrid-5_8-White.jpg', 'colors' => array('White')),
        array('name' => 'Sculpted Grid 1″', 'image' => '2025/06/SculptedGrid-1-White.jpg', 'colors' => array('White')),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/picture-windows/aluminum' => array(
      'name' => 'Aluminum Picture Window',
      'series' => 'aluminum',
      'style' => 'picture',
      'legacy' => '/products/picture-windows/aluminum-picture-window/',
      'lead' => 'Picture windows are the perfect fixed stress-free solution to enjoy your dream view with maximum sealing for energy efficiency.',
      'views' => array(array('', '2020/05/Aluminum-Picture_.jpg')),
      'highlights' => array('Slim Sightlines', 'Thermal Superiority', 'Modern Aesthetic'),
      'material' => 'Aluminum',
      'exterior' => array('Clear Anodized', 'Bronze Anodized'),
      'interior' => array('Clear Anodized', 'Bronze Anodized'),
      'blinds' => false,
      'features' => array('20 mil Anodized Protection'),
      'glazing' => array(),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/4″',
      'frame_options' => array('Retrofit 2″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2022/04/Aluminum-Block.jpg',
        'Nail-On' => '2022/04/Aluminum-Nail-on_.jpg',
        'Retrofit' => '2022/04/Aluminum-Retro-Fit_.jpg',
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/casement-awning-windows/zenith' => array(
      'name' => 'Zenith Casement & Awning Window',
      'series' => 'zenith',
      'style' => 'casement-awning',
      'legacy' => '/products/casement-and-awning-windows/zenith-casement-awning-window/',
      'lead' => 'Provide light and ventilation in even the smallest locations and versatile configurations. Casements open in full 90 degrees in left or right configurations',
      'views' => array(
        array('Standard', '2024/10/PRM_Web-Zenith-Hero_0016_ZE_UNIT-CM.png'),
        array('Blinds outside', '2024/10/PRM_Web-Zenith-Hero_0017_ZE_UNIT-CM-ODL.png'),
        array('Blinds inside', '2024/10/PRM_Web-Zenith-Hero_0018_ZE_UNIT-CM-ODL-IN.png'),
        array('Operator', '2024/10/PRM_Web-Zenith-Hero_0019_ZE_UNIT-CM-ODL-IN-IG.png'),
      ),
      'highlights' => array('Elevated Luxury Experience', 'Cutting-Edge Performance Vinyl', 'Versatile Style Integration'),
      'material' => 'Performance Vinyl',
      'exterior' => array('Black'),
      'interior' => array('Black'),
      'blinds' => true,
      'benefits' => array(
        'title' => 'Performance Vinyl Benefits',
        'text' => 'Our innovative formula and performance co-extruded frames maintain the perfect balance between your desired luxury look and durability in the hottest of climates.',
        'items' => array('200°F Heat Resistance', 'Anti-Warping', 'Anti-Shrinking', 'Color-Fade Resistance'),
      ),
      'features' => array('Capstock Protection', 'Enhanced Hardware', 'Weather Sealed Bead'),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Streamlined Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/2″',
      'frame_options' => array('Retrofit 2-1/2″', 'Nail-On 1″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2024/10/ZeDeet-CM-BL-DUP.jpg',
        'Nail-On' => '2024/10/ZeDeet-CM-NO1-DRP.jpg',
        'Retrofit' => '2024/10/ZeDeet-CM-R2-DRP.jpg',
      ),
      'grids' => array(
        array('name' => 'Flat Grid 3/4″', 'image' => '2025/06/FlatGrid-3_4-Black.jpg', 'colors' => array('Black')),
        array('name' => 'Flat Grid 5/8″', 'image' => '2025/06/FlatGrid-5_8-Black.jpg', 'colors' => array('Black')),
        array('name' => 'Sculpted Grid 1″', 'image' => '2025/06/SculptedGrid-1-Black.jpg', 'colors' => array('Black')),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/casement-awning-windows/serene' => array(
      'name' => 'Serene Casement & Awning Window',
      'series' => 'serene',
      'style' => 'casement-awning',
      'legacy' => '/products/casement-and-awning-windows/serene-series-casement-awning-window/',
      'lead' => 'Provide light and ventilation in even the smallest locations and versatile configurations. Casements open in full 90 degrees in left or right configurations',
      'views' => array(array('', '2020/04/Thumb-Windows-Casement-Awning-Serene.jpg')),
      'highlights' => array('Sound Reduction', 'Energy Efficiency', 'Even Sightlines', 'Design Versatility'),
      'material' => 'Vinyl',
      'exterior' => array('White', 'Almond', 'Black Laminated'),
      'interior' => array('White', 'Almond'),
      'blinds' => true,
      'features' => array('Even Sightlines', 'Standard Hardware', 'Standard Glazing Bead'),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/2″',
      'frame_options' => array('Retrofit 1-3/4″', 'Nail-On 1″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2022/03/Frame_detail-Block.jpg',
        'Nail-On' => '2022/03/Frame_detail-Nailon.jpg',
        'Retrofit' => '2022/03/Frame_detail-Retrofit.jpg',
      ),
      'grids' => array(
        array(
          'name' => 'Flat Grid 3/4″',
          'image' => '2025/06/FlatGrid-3_4-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
        array(
          'name' => 'Flat Grid 5/8″',
          'image' => '2025/06/FlatGrid-5_8-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
        array(
          'name' => 'Sculpted Grid 1″',
          'image' => '2025/06/SculptedGrid-1-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/casement-awning-windows/aluminum' => array(
      'name' => 'Aluminum Casement & Awning Window',
      'series' => 'aluminum',
      'style' => 'casement-awning',
      'legacy' => '/products/casement-and-awning-windows/aluminum-casement-awing-window/',
      'lead' => 'Provide light and ventilation in even the smallest locations and versatile configurations. Casements open in full 90 degrees in left or right configurations',
      'views' => array(array('', '2020/05/Casement-Window-Aluminum-Series-1.jpg')),
      'highlights' => array('Slim Sightlines', 'Thermal Superiority', 'Modern Aesthetic'),
      'material' => 'Aluminum',
      'exterior' => array('Clear Anodized', 'Bronze Anodized'),
      'interior' => array('Clear Anodized', 'Bronze Anodized'),
      'blinds' => false,
      'features' => array('20 mil Anodized Protection'),
      'glazing' => array(),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/4″',
      'frame_options' => array('Retrofit 2″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2022/04/Aluminum-Block.jpg',
        'Nail-On' => '2022/04/Aluminum-Nail-on_.jpg',
        'Retrofit' => '2022/04/Aluminum-Retro-Fit_.jpg',
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/horizontal-sliding-windows/zenith' => array(
      'name' => 'Zenith Horizontal Sliding Window',
      'series' => 'zenith',
      'style' => 'horizontal-sliding',
      'legacy' => '/products/horizontal-sliding-windows/zenith-horizontal-sliding-window/',
      'lead' => 'Horizontal sliding windows are popular for combining natural light and fresh air flow in small or larger openings. A versatile solution with smooth sliding operation to the left or right.',
      'views' => array(
        array('Standard', '2024/10/PRM_Web-Zenith-Hero_0012_ZE_UNIT-XO.png'),
        array('Blinds outside', '2024/10/PRM_Web-Zenith-Hero_0013_ZE_UNIT-XO-ODL.png'),
        array('Blinds inside', '2024/10/PRM_Web-Zenith-Hero_0014_ZE_UNIT-XO-ODL-IN.png'),
        array('Operator', '2024/10/PRM_Web-Zenith-Hero_0015_ZE_UNIT-XO-ODL-IN-IG.png'),
      ),
      'highlights' => array('Elevated Luxury Experience', 'Cutting-Edge Performance Vinyl', 'Versatile Style Integration'),
      'material' => 'Performance Vinyl',
      'exterior' => array('Black'),
      'interior' => array('Black'),
      'blinds' => true,
      'benefits' => array(
        'title' => 'Performance Vinyl Benefits',
        'text' => 'Our innovative formula and performance co-extruded frames maintain the perfect balance between your desired luxury look and durability in the hottest of climates.',
        'items' => array('200°F Heat Resistance', 'Anti-Warping', 'Anti-Shrinking', 'Color-Fade Resistance'),
      ),
      'features' => array(
        'Capstock Protection',
        'Smooth Glide Rollers & Rail',
        'Standard Hardware',
        'Sash Auto Lock',
        'Integral Handle',
        'Weather Sealed Bead',
      ),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Streamlined Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/2″',
      'frame_options' => array('Retrofit 2-1/2″', 'Nail-On 1″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2024/10/ZeDeet-XO-BL-TRP.jpg',
        'Nail-On' => '2024/10/ZeDeet-XO-N1-DRP.jpg',
        'Retrofit' => '2024/10/ZeDeet-XO-R2-DP.jpg',
      ),
      'hardware' => array(
        array('name' => 'Sash Auto-Lock', 'image' => '2025/06/Hardware-Sash_Loc-Black.jpg', 'colors' => array('White')),
      ),
      'grids' => array(
        array('name' => 'Flat Grid 3/4″', 'image' => '2025/06/FlatGrid-3_4-Black.jpg', 'colors' => array('Black')),
        array('name' => 'Flat Grid 5/8″', 'image' => '2025/06/FlatGrid-5_8-Black.jpg', 'colors' => array('Black')),
        array('name' => 'Sculpted Grid 1″', 'image' => '2025/06/SculptedGrid-1-Black.jpg', 'colors' => array('Black')),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/horizontal-sliding-windows/timeless' => array(
      'name' => 'Timeless Horizontal Sliding Window',
      'series' => 'timeless',
      'style' => 'horizontal-sliding',
      'legacy' => '/products/horizontal-sliding-windows/timeless-series-horizontal-sliding-window/',
      'lead' => 'Horizontal sliding windows are popular for combining natural light and fresh air flow in small or larger openings. A versatile solution with smooth sliding operation to the left or right.',
      'views' => array(array('', '2025/12/PRM_Web-Timeless-Hero_0006_TI_UNIT-XO.png')),
      'highlights' => array('Premium Durability', 'Narrow Frames', 'Maximized Value'),
      'material' => 'Vinyl',
      'exterior' => array('White', 'Almond', 'Black Laminated'),
      'interior' => array('White', 'Almond'),
      'blinds' => false,
      'features' => array('Nylon Rollers & Rail', 'Standard Hardware', 'Sash Auto Lock', 'Integral Handle', 'Standard Glazing Bead'),
      'glazing' => array('Dual Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/4″ • 2-3/4″ (Nail-On 1″ & Block)',
      'frame_options' => array('Retrofit 1-3/4″', 'Retrofit 2-1/2″', 'Nail-On 1″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2025/10/04_TimeDeet-XO-BK.jpg',
        'Nail-On' => '2025/10/02_TimeDeet-XO-N13.jpg',
        'Retrofit' => '2025/10/00_TimeDeet-XO-R2.jpg',
      ),
      'hardware' => array(
        array('name' => 'Sash Auto-Lock', 'image' => '2025/06/Hardware-Sash_Loc-White.jpg', 'colors' => array('White')),
      ),
      'grids' => array(
        array(
          'name' => 'Flat Grid 3/4″',
          'image' => '2025/06/FlatGrid-3_4-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
        array(
          'name' => 'Flat Grid 5/8″',
          'image' => '2025/06/FlatGrid-5_8-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
        array(
          'name' => 'Sculpted Grid 1″',
          'image' => '2025/06/SculptedGrid-1-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/horizontal-sliding-windows/serene' => array(
      'name' => 'Serene Horizontal Sliding Window',
      'series' => 'serene',
      'style' => 'horizontal-sliding',
      'legacy' => '/products/horizontal-sliding-windows/serene-series-horizontal-sliding-window/',
      'lead' => 'Horizontal sliding windows are popular for combining natural light and fresh air flow in small or larger openings. A versatile solution with smooth sliding operation to the left or right.',
      'views' => array(array('', '2022/04/SereneW-Horizontal_Sliding-3D_TURNTABLE-RETROFIT-0001.png')),
      'highlights' => array('Sound Reduction', 'Energy Efficiency', 'Even Sightlines', 'Design Versatility'),
      'material' => 'Vinyl',
      'exterior' => array('White'),
      'interior' => array('White'),
      'blinds' => true,
      'features' => array(
        'Even Sightlines',
        'Smooth Glide Rollers & Rail',
        'Vent Latches',
        'Sash Auto Lock',
        'Integral Handle',
        'Standard Glazing Bead',
      ),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/2″',
      'frame_options' => array('Retrofit 1-3/4″', 'Nail-On 1″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2022/03/Frame_detail-Block.jpg',
        'Nail-On' => '2022/03/Frame_detail-Nailon.jpg',
        'Retrofit' => '2022/03/Frame_detail-Retrofit.jpg',
      ),
      'hardware' => array(
        array('name' => 'Sash Auto-Lock', 'image' => '2025/06/Hardware-Sash_Loc-White.jpg', 'colors' => array('White')),
      ),
      'grids' => array(
        array('name' => 'Flat Grid 3/4″', 'image' => '2025/06/FlatGrid-3_4-White.jpg', 'colors' => array('White')),
        array('name' => 'Flat Grid 5/8″', 'image' => '2025/06/FlatGrid-5_8-White.jpg', 'colors' => array('White')),
        array('name' => 'Sculpted Grid 1″', 'image' => '2025/06/SculptedGrid-1-White.jpg', 'colors' => array('White')),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/horizontal-sliding-windows/elegance' => array(
      'name' => 'Elegance Horizontal Sliding Window',
      'series' => 'elegance',
      'style' => 'horizontal-sliding',
      'legacy' => '/products/horizontal-sliding-windows/infinite-series-horizontal-sliding-window/',
      'lead' => 'Horizontal sliding windows are popular for combining natural light and fresh air flow in small or larger openings. A versatile solution with smooth sliding operation to the left or right.',
      'views' => array(array('', '2025/12/PRM_Web-Elegance-Hero_0002_EL_UNIT-XO.png')),
      'highlights' => array('Classic Styling', 'Even SightLines', 'Premium Durability'),
      'material' => 'Vinyl',
      'exterior' => array('White'),
      'interior' => array('White'),
      'blinds' => false,
      'features' => array(
        'Nylon Rollers & Rail',
        'Standard Hardware',
        'Vent Latches',
        'Sash Auto Lock',
        'Integral Handle',
        'Standard Glazing Bead',
      ),
      'glazing' => array('Dual Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '2-3/4″',
      'frame_options' => array('Retrofit 1-3/4″', 'Nail-On 1″', 'Block'),
      'frame_details' => array(
        'Block' => '2025/10/02_ElegDeet-XO-BK.jpg',
        'Nail-On' => '2025/10/01_ElegDeet-XO-N1.jpg',
        'Retrofit' => '2025/10/00_ElegDeet-XO-R1.jpg',
      ),
      'hardware' => array(
        array('name' => 'Sash Auto-Lock', 'image' => '2025/06/Hardware-Sash_Loc-White.jpg', 'colors' => array('White')),
      ),
      'grids' => array(
        array('name' => 'Flat Grid 3/4″', 'image' => '2025/06/FlatGrid-3_4-White.jpg', 'colors' => array('White')),
        array('name' => 'Flat Grid 5/8″', 'image' => '2025/06/FlatGrid-5_8-White.jpg', 'colors' => array('White')),
        array('name' => 'Sculpted Grid 1″', 'image' => '2025/06/SculptedGrid-1-White.jpg', 'colors' => array('White')),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/horizontal-sliding-windows/aluminum' => array(
      'name' => 'Aluminum Horizontal Sliding Window',
      'series' => 'aluminum',
      'style' => 'horizontal-sliding',
      'legacy' => '/products/horizontal-sliding-windows/aluminum-picture-window/',
      'lead' => 'Horizontal sliding windows are popular for combining natural light and fresh air flow in small or larger openings. A versatile solution with smooth sliding operation to the left or right.',
      'views' => array(array('', '2020/05/Horizontal-Slider.jpg')),
      'highlights' => array('Slim Sightlines', 'Thermal Superiority', 'Modern Aesthetic'),
      'material' => 'Aluminum',
      'exterior' => array('Clear Anodized', 'Bronze Anodized'),
      'interior' => array('Clear Anodized', 'Bronze Anodized'),
      'blinds' => false,
      'features' => array('20 mil Anodized Protection'),
      'glazing' => array(),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/4″',
      'frame_options' => array('Retrofit 2″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2022/04/Aluminum-Block.jpg',
        'Nail-On' => '2022/04/Aluminum-Nail-on_.jpg',
        'Retrofit' => '2022/04/Aluminum-Retro-Fit_.jpg',
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/single-hung-windows/zenith' => array(
      'name' => 'Zenith Single Hung Window',
      'series' => 'zenith',
      'style' => 'single-hung',
      'legacy' => '/products/single-hung-windows/zenith-single-hung-window/',
      'lead' => 'Single hung windows are a classic solution with a smooth single vertical operable sash.',
      'views' => array(
        array('Standard', '2024/10/PRM_Web-Zenith-Hero_0006_ZE_UNIT-SH.png'),
        array('Blinds outside', '2024/10/PRM_Web-Zenith-Hero_0007_ZE_UNIT-SH-ODL.png'),
        array('Blinds inside', '2024/10/PRM_Web-Zenith-Hero_0005_ZE_UNIT-SH-ODL-IN-1.png'),
        array('Operator', '2024/10/PRM_Web-Zenith-Hero_0004_ZE_UNIT-SH-ODL-IN_IG.png'),
      ),
      'highlights' => array('Elevated Luxury Experience', 'Cutting-Edge Performance Vinyl', 'Versatile Style Integration'),
      'material' => 'Performance Vinyl',
      'exterior' => array('Black'),
      'interior' => array('Black'),
      'blinds' => true,
      'benefits' => array(
        'title' => 'Performance Vinyl Benefits',
        'text' => 'Our innovative formula and performance co-extruded frames maintain the perfect balance between your desired luxury look and durability in the hottest of climates.',
        'items' => array('200°F Heat Resistance', 'Anti-Warping', 'Anti-Shrinking', 'Color-Fade Resistance'),
      ),
      'features' => array(
        'Capstock Protection',
        'Single Pane TILT-OUT',
        'Standard Hardware',
        'Sash Auto Lock',
        'Integral Handle',
        'Weather Sealed Bead',
      ),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Streamlined Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/2″',
      'frame_options' => array('Retrofit 2-1/2″', 'Nail-On 1″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2024/10/ZeDeet-SH-BL-TRP.jpg',
        'Nail-On' => '2024/10/ZeDeet-SH-N1-DRP.jpg',
        'Retrofit' => '2024/10/ZeDeet-SH-N1-DRP.jpg',
      ),
      'hardware' => array(
        array('name' => 'Sash Auto-Lock', 'image' => '2025/06/Hardware-Sash_Loc-Black.jpg', 'colors' => array('White')),
      ),
      'grids' => array(
        array('name' => 'Flat Grid 3/4″', 'image' => '2025/06/FlatGrid-3_4-Black.jpg', 'colors' => array('Black')),
        array('name' => 'Flat Grid 5/8″', 'image' => '2025/06/FlatGrid-5_8-Black.jpg', 'colors' => array('Black')),
        array('name' => 'Sculpted Grid 1″', 'image' => '2025/06/SculptedGrid-1-Black.jpg', 'colors' => array('Black')),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/single-hung-windows/timeless' => array(
      'name' => 'Timeless Single Hung Window',
      'series' => 'timeless',
      'style' => 'single-hung',
      'legacy' => '/products/single-hung-windows/timeless-series-single-hung-window/',
      'lead' => 'Single hung windows are a classic solution with a smooth single vertical operable sash.',
      'views' => array(array('', '2025/12/PRM_Web-Timeless-Hero_0004_TI_UNIT-SH.png')),
      'highlights' => array('Premium Durability', 'Narrow Frames', 'Maximized Value'),
      'material' => 'Vinyl',
      'exterior' => array('White', 'Almond', 'Black Laminated'),
      'interior' => array('White', 'Almond'),
      'blinds' => false,
      'features' => array(
        'Non-Tilt Balance System',
        'Standard Hardware',
        'Sash Auto Lock',
        'Integral Handle',
        'Standard Glazing Bead',
      ),
      'glazing' => array('Dual Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/4″ • 2-3/4″ (Nail-On 1″ & Block)',
      'frame_options' => array('Retrofit 1-3/4″', 'Retrofit 2-1/2″', 'Nail-On 1″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2025/10/09_TimeDeet-SH-BK.jpg',
        'Nail-On' => '2025/10/07_TimeDeet-SH-N13.jpg',
        'Retrofit' => '2025/10/05_TimeDeet-SH-R2.jpg',
      ),
      'hardware' => array(
        array('name' => 'Sash Auto-Lock', 'image' => '2025/06/Hardware-Sash_Loc-White.jpg', 'colors' => array('White')),
      ),
      'grids' => array(
        array(
          'name' => 'Flat Grid 3/4″',
          'image' => '2025/06/FlatGrid-3_4-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
        array(
          'name' => 'Flat Grid 5/8″',
          'image' => '2025/06/FlatGrid-5_8-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
        array(
          'name' => 'Sculpted Grid 1″',
          'image' => '2025/06/SculptedGrid-1-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/single-hung-windows/serene' => array(
      'name' => 'Serene Single Hung Window',
      'series' => 'serene',
      'style' => 'single-hung',
      'legacy' => '/products/single-hung-windows/serene-series-tilt-in-single-hung-window/',
      'lead' => 'Single hung windows are a classic solution with a smooth single vertical operable sash.',
      'views' => array(array('', '2022/04/SereneW-Single_Hung-3D_TURNTABLE-RETROFIT-0001.png')),
      'highlights' => array('Sound Reduction', 'Energy Efficiency', 'Even Sightlines', 'Design Versatility'),
      'material' => 'Vinyl',
      'exterior' => array('White'),
      'interior' => array('White'),
      'blinds' => true,
      'features' => array(
        'Even Sightlines',
        'Single Pane TILT-OUT',
        'Standard Hardware',
        'Vent Latches',
        'Sash Auto Lock',
        'Integral Handle',
        'Standard Glazing Bead',
      ),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/2″',
      'frame_options' => array('Retrofit 1-3/4″', 'Nail-On 1″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2022/03/Frame_detail-Block.jpg',
        'Nail-On' => '2022/03/Frame_detail-Nailon.jpg',
        'Retrofit' => '2022/03/Frame_detail-Retrofit.jpg',
      ),
      'hardware' => array(
        array('name' => 'Sash Auto-Lock', 'image' => '2025/06/Hardware-Sash_Loc-White.jpg', 'colors' => array('White')),
      ),
      'grids' => array(
        array('name' => 'Flat Grid 3/4″', 'image' => '2025/06/FlatGrid-3_4-White.jpg', 'colors' => array('White')),
        array('name' => 'Flat Grid 5/8″', 'image' => '2025/06/FlatGrid-5_8-White.jpg', 'colors' => array('White')),
        array('name' => 'Sculpted Grid 1″', 'image' => '2025/06/SculptedGrid-1-White.jpg', 'colors' => array('White')),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/single-hung-windows/elegance' => array(
      'name' => 'Elegance Single Hung Window',
      'series' => 'elegance',
      'style' => 'single-hung',
      'legacy' => '/products/single-hung-windows/infinite-series-single-hung-window/',
      'lead' => 'Single hung windows are a classic solution with a smooth single vertical operable sash.',
      'views' => array(array('', '2025/12/PRM_Web-Elegance-Hero_0000_EL_UNIT-SH.png')),
      'highlights' => array('Classic Styling', 'Even SightLines', 'Premium Durability'),
      'material' => 'Vinyl',
      'exterior' => array('White'),
      'interior' => array('White'),
      'blinds' => false,
      'features' => array(
        'Single Pane TILT-OUT',
        'Standard Hardware',
        'Vent Latches',
        'Sash Auto Lock',
        'Integral Handle',
        'Standard Glazing Bead',
      ),
      'glazing' => array('Dual Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '2-3/4″',
      'frame_options' => array('Retrofit 1-3/4″', 'Nail-On 1″', 'Block'),
      'frame_details' => array(
        'Block' => '2025/10/05_ElegDeet-SH-BK.jpg',
        'Nail-On' => '2025/10/04_ElegDeet-SH-N1.jpg',
        'Retrofit' => '2025/10/03_ElegDeet-SH-R1.jpg',
      ),
      'hardware' => array(
        array('name' => 'Sash Auto-Lock', 'image' => '2025/06/Hardware-Sash_Loc-White.jpg', 'colors' => array('White')),
      ),
      'grids' => array(
        array('name' => 'Flat Grid 3/4″', 'image' => '2025/06/FlatGrid-3_4-White.jpg', 'colors' => array('White')),
        array('name' => 'Flat Grid 5/8″', 'image' => '2025/06/FlatGrid-5_8-White.jpg', 'colors' => array('White')),
        array('name' => 'Sculpted Grid 1″', 'image' => '2025/06/SculptedGrid-1-White.jpg', 'colors' => array('White')),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/single-hung-windows/aluminum' => array(
      'name' => 'Aluminum Single Hung Window',
      'series' => 'aluminum',
      'style' => 'single-hung',
      'legacy' => '/products/single-hung-windows/aluminum-single-hung-window/',
      'lead' => 'Single hung windows are a classic solution with a smooth single vertical operable sash.',
      'views' => array(array('', '2020/05/Aluminum-Series-Single-Hung-Window.jpg')),
      'highlights' => array('Slim Sightlines', 'Thermal Superiority', 'Modern Aesthetic'),
      'material' => 'Aluminum',
      'exterior' => array('Clear Anodized', 'Bronze Anodized'),
      'interior' => array('Clear Anodized', 'Bronze Anodized'),
      'blinds' => false,
      'features' => array('20 mil Anodized Protection'),
      'glazing' => array(),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/4″',
      'frame_options' => array('Retrofit 2″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2022/04/Aluminum-Block.jpg',
        'Nail-On' => '2022/04/Aluminum-Nail-on_.jpg',
        'Retrofit' => '2022/04/Aluminum-Retro-Fit_.jpg',
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/double-hung-windows/zenith' => array(
      'name' => 'Zenith Double Hung Window',
      'series' => 'zenith',
      'style' => 'double-hung',
      'legacy' => '/products/double-hung-windows/zenith-double-hung-window/',
      'lead' => 'Double hung windows offer maximum light and maximum air flow with dual tilting sashes in any desired location.',
      'views' => array(
        array('Standard', '2024/09/PRM_Web-Zenith-Hero_0008_ZE_UNIT-DH.png'),
        array('Blinds outside', '2024/09/PRM_Web-Zenith-Hero_0009_ZE_UNIT-DH-ODL.png'),
        array('Blinds inside', '2024/09/PRM_Web-Zenith-Hero_0010_ZE_UNIT-DH-ODL-IN.png'),
        array('Operator', '2024/09/PRM_Web-Zenith-Hero_0011_ZE_UNIT-DH-ODL-IN-IG.png'),
      ),
      'highlights' => array('Elevated Luxury Experience', 'Cutting-Edge Performance Vinyl', 'Versatile Style Integration'),
      'material' => 'Performance Vinyl',
      'exterior' => array('Black'),
      'interior' => array('Black'),
      'blinds' => true,
      'benefits' => array(
        'title' => 'Performance Vinyl Benefits',
        'text' => 'Our innovative formula and performance co-extruded frames maintain the perfect balance between your desired luxury look and durability in the hottest of climates.',
        'items' => array('200°F Heat Resistance', 'Anti-Warping', 'Anti-Shrinking', 'Color-Fade Resistance'),
      ),
      'features' => array(
        'Capstock Protection',
        'Double Pane TILT-OUT',
        'Standard Hardware',
        'Sash Auto Lock',
        'Integral Handle',
        'Weather Sealed Bead',
      ),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Streamlined Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/2″',
      'frame_options' => array('Retrofit 2-1/2″', 'Nail-On 1″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2024/09/ZeDeet-DH-BL-TRP.jpg',
        'Nail-On' => '2024/09/ZeDeet-DH-NO13-DRP.jpg',
        'Retrofit' => '2024/09/ZeDeet-DH-R2-DUP.jpg',
      ),
      'hardware' => array(
        array('name' => 'Sash Auto-Lock', 'image' => '2025/06/Hardware-Sash_Loc-Black.jpg', 'colors' => array('White')),
      ),
      'grids' => array(
        array('name' => 'Flat Grid 3/4″', 'image' => '2025/06/FlatGrid-3_4-Black.jpg', 'colors' => array('Black')),
        array('name' => 'Flat Grid 5/8″', 'image' => '2025/06/FlatGrid-5_8-Black.jpg', 'colors' => array('Black')),
        array('name' => 'Sculpted Grid 1″', 'image' => '2025/06/SculptedGrid-1-Black.jpg', 'colors' => array('Black')),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/double-hung-windows/serene' => array(
      'name' => 'Serene Double Hung Window',
      'series' => 'serene',
      'style' => 'double-hung',
      'legacy' => '/products/double-hung-windows/serene-series-double-hung-window/',
      'lead' => 'Double hung windows offer maximum light and maximum air flow with dual tilting sashes in any desired location.',
      'views' => array(array('', '2022/05/SereneW-Double_Hung-3D_TURNTABLE-RETROFIT-0001.png')),
      'highlights' => array('Sound Reduction', 'Energy Efficiency', 'Even Sightlines', 'Design Versatility'),
      'material' => 'Vinyl',
      'exterior' => array('White'),
      'interior' => array('White'),
      'blinds' => true,
      'features' => array(
        'Even Sightlines',
        'Double Pane TILT-OUT',
        'Standard Hardware',
        'Vent Latches',
        'Sash Auto Lock',
        'Integral Handle',
        'Standard Glazing Bead',
      ),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/2″',
      'frame_options' => array('Retrofit 1-3/4″', 'Nail-On 1″', 'Nail-On 1-3/8″', 'Block'),
      'frame_details' => array(
        'Block' => '2022/03/Frame_detail-Block.jpg',
        'Nail-On' => '2022/03/Frame_detail-Nailon.jpg',
        'Retrofit' => '2022/03/Frame_detail-Retrofit.jpg',
      ),
      'hardware' => array(
        array('name' => 'Sash Auto-Lock', 'image' => '2025/06/Hardware-Sash_Loc-White.jpg', 'colors' => array('White')),
      ),
      'grids' => array(
        array('name' => 'Flat Grid 3/4″', 'image' => '2025/06/FlatGrid-3_4-White.jpg', 'colors' => array('White')),
        array('name' => 'Flat Grid 5/8″', 'image' => '2025/06/FlatGrid-5_8-White.jpg', 'colors' => array('White')),
        array('name' => 'Sculpted Grid 1″', 'image' => '2025/06/SculptedGrid-1-White.jpg', 'colors' => array('White')),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/arch-special-shape-windows/timeless' => array(
      'name' => 'Timeless Arch Window',
      'series' => 'timeless',
      'style' => 'arch-special-shape',
      'legacy' => '/products/arch-and-special-shape-windows/timeless-series-arch-window/',
      'lead' => 'Arch windows have a single fixed non-venting opening and feature a curved or half-circle top portion. Special shape windows are perfect for maximising natural light in angled ceiling areas.',
      'views' => array(array('', '2025/12/PRM_Web-Timeless-Hero_0007_TI_UNIT-ARC.png')),
      'highlights' => array('Premium Durability', 'Narrow Frames', 'Maximized Value'),
      'material' => 'Vinyl',
      'exterior' => array('White', 'Almond', 'Black Laminated'),
      'interior' => array('White', 'Almond'),
      'blinds' => false,
      'features' => array('Standard Glazing Bead'),
      'glazing' => array('Dual Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '3-1/4″ • 2-3/4″ (Nail-On 1″ & Block)',
      'frame_options' => array('Retrofit 1-3/4″', 'Retrofit 2-1/2″', 'Nail-On 1″', 'Block'),
      'frame_details' => array(
        'Block' => '2025/10/14_TimeDeet-PW-BK.jpg',
        'Nail-On' => '2025/10/12_TimeDeet-PW-N13.jpg',
        'Retrofit' => '2025/10/10_TimeDeet-PW-R2.jpg',
      ),
      'grids' => array(
        array(
          'name' => 'Flat Grid 3/4″',
          'image' => '2025/06/FlatGrid-3_4-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
        array(
          'name' => 'Flat Grid 5/8″',
          'image' => '2025/06/FlatGrid-5_8-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
        array(
          'name' => 'Sculpted Grid 1″',
          'image' => '2025/06/SculptedGrid-1-White.jpg',
          'colors' => array('White', 'Almond', 'Black'),
        ),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'windows/arch-special-shape-windows/elegance' => array(
      'name' => 'Elegance Arch Window',
      'series' => 'elegance',
      'style' => 'arch-special-shape',
      'legacy' => '/products/arch-and-special-shape-windows/infinite-series-arch-window/',
      'lead' => 'Arch windows have a single fixed non-venting opening and feature a curved or half-circle top portion. Special shape windows are perfect for maximising natural light in angled ceiling areas.',
      'views' => array(array('', '2025/12/PRM_Web-Elegance-Hero_0003_EL_UNIT-ARC.png')),
      'highlights' => array('Classic Styling', 'Even SightLines', 'Premium Durability'),
      'material' => 'Vinyl',
      'exterior' => array('White'),
      'interior' => array('White'),
      'blinds' => false,
      'features' => array('Standard Glazing Bead'),
      'glazing' => array('Dual Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
      'frame_depth' => '2-3/4″',
      'frame_options' => array('Retrofit 1-3/4″', 'Nail-On 1″', 'Block'),
      'frame_details' => array(
        'Block' => '2020/03/Elegance-Framing-Detail-Diagram_0002_ElegDeet-PW-BK.jpg',
        'Nail-On' => '2020/03/Elegance-Framing-Detail-Diagram_0001_ElegDeet-PW-N1.jpg',
        'Retrofit' => '2020/03/Elegance-Framing-Detail-Diagram_0000_ElegDeet-PW-R1.jpg',
      ),
      'grids' => array(
        array('name' => 'Flat Grid 3/4″', 'image' => '2025/06/FlatGrid-3_4-White.jpg', 'colors' => array('White')),
        array('name' => 'Flat Grid 5/8″', 'image' => '2025/06/FlatGrid-5_8-White.jpg', 'colors' => array('White')),
        array('name' => 'Sculpted Grid 1″', 'image' => '2025/06/SculptedGrid-1-White.jpg', 'colors' => array('White')),
      ),
      'textures' => array('Obscure', 'Reed', 'Rain', 'Glue Chip', 'Flemish'),
    ),
    'doors/patio-sliding-doors/zenith' => array(
      'name' => 'Zenith Patio Sliding Door',
      'series' => 'zenith',
      'style' => 'patio-sliding',
      'legacy' => '/products/patio-sliding-doors/zenith-patio-sliding-door/',
      'lead' => 'Patio sliding doors have 1 or 2 operable sashes in multiple configuration options.',
      'views' => array(
        array('Standard', '2024/10/PRM_Web-Zenith-Hero_0024_ZE_UNIT-SL.png'),
        array('Blinds outside', '2024/10/PRM_Web-Zenith-Hero_0025_ZE_UNIT-SL-ODL.png'),
        array('Blinds inside', '2024/10/PRM_Web-Zenith-Hero_0026_ZE_UNIT-SL-ODL-IN.png'),
        array('Operator', '2024/10/PRM_Web-Zenith-Hero_0027_ZE_UNIT-SL-ODL-IN-IG.png'),
      ),
      'highlights' => array('Elevated Luxury Experience', 'Cutting-Edge Performance Vinyl', 'Versatile Style Integration'),
      'material' => 'Performance Vinyl',
      'exterior' => array('Black'),
      'interior' => array('Black'),
      'blinds' => true,
      'benefits' => array(
        'title' => 'Performance Vinyl Benefits',
        'text' => 'Our innovative formula and performance co-extruded frames maintain the perfect balance between your desired luxury look and durability in the hottest of climates.',
        'items' => array('200°F Heat Resistance', 'Anti-Warping', 'Anti-Shrinking', 'Color-Fade Resistance'),
      ),
      'features' => array(
        'Capstock Protection',
        'Thin & Thick Sashes',
        'Enhanced Hardware',
        'Key Lock Option Available',
        'Even Sightlines',
      ),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Streamlined Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
    ),
    'doors/patio-sliding-doors/timeless' => array(
      'name' => 'Timeless Patio Sliding Door',
      'series' => 'timeless',
      'style' => 'patio-sliding',
      'legacy' => '/products/patio-sliding-doors/timeless-series-patio-sliding-door/',
      'lead' => 'Patio sliding doors have 1 or 2 operable sashes in multiple configuration options.',
      'views' => array(array('', '2020/03/TI_Unit-SL.png')),
      'highlights' => array('Premium Durability', 'Narrow Frames', 'Maximized Value'),
      'material' => 'Vinyl',
      'exterior' => array('White', 'Almond', 'Black Laminated'),
      'interior' => array('White', 'Almond'),
      'blinds' => false,
      'features' => array('Slim Door Sash', 'Standard Hardware', 'Key Lock Option Available', 'Even Sightlines'),
      'glazing' => array('Dual Pane', 'Dura Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
    ),
    'doors/patio-sliding-doors/serene' => array(
      'name' => 'Serene Patio Sliding Door',
      'series' => 'serene',
      'style' => 'patio-sliding',
      'legacy' => '/products/patio-sliding-doors/serene-series-patio-sliding-door/',
      'lead' => 'Patio sliding doors have 1 or 2 operable sashes in multiple configuration options.',
      'views' => array(array('', '2020/04/Thumb-Doors-Patio-Sliding-Serene.jpg')),
      'highlights' => array('Sound Reduction', 'Energy Efficiency', 'Even Sightlines', 'Design Versatility'),
      'material' => 'Vinyl',
      'exterior' => array('White', 'Almond', 'Black Laminated'),
      'interior' => array('White', 'Almond'),
      'blinds' => true,
      'features' => array('Thick Door Sash', 'Standard Hardware', 'Key Lock Option Available', 'Even Sightlines'),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
    ),
    'doors/patio-sliding-doors/elegance' => array(
      'name' => 'Elegance Patio Sliding Door',
      'series' => 'elegance',
      'style' => 'patio-sliding',
      'legacy' => '/products/patio-sliding-doors/infinite-series-patio-sliding-door/',
      'lead' => 'Patio sliding doors have 1 or 2 operable sashes in multiple configuration options.',
      'views' => array(array('', '2020/05/Infinite-Patio-Door.jpg')),
      'highlights' => array('Classic Styling', 'Even SightLines', 'Premium Durability'),
      'material' => 'Vinyl',
      'exterior' => array('White'),
      'interior' => array('White'),
      'blinds' => false,
      'features' => array('Thick Door Sash', 'Standard Hardware', 'Key Lock Option Available', 'Even Sightlines'),
      'glazing' => array('Dual Pane', 'Dura Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
    ),
    'doors/patio-sliding-doors/aluminum' => array(
      'name' => 'Aluminum Patio Sliding Door',
      'series' => 'aluminum',
      'style' => 'patio-sliding',
      'legacy' => '/products/patio-sliding-doors/aluminum-patio-sliding-door/',
      'lead' => 'Patio sliding doors have 1 or 2 operable sashes in multiple configuration options.',
      'views' => array(array('', '2020/03/Patio-Sliding-Aluminum-Door.jpg')),
      'highlights' => array('Slim Sightlines', 'Thermal Superiority', 'Modern Aesthetic'),
      'material' => 'Aluminum',
      'exterior' => array('Clear Anodized', 'Bronze Anodized'),
      'interior' => array('Clear Anodized', 'Bronze Anodized'),
      'blinds' => false,
      'features' => array(
        '20 mil Anodized Protection',
        'Slim Door Sash',
        'Enhanced Hardware',
        'Key Lock Option Available',
        'Even Sightlines',
      ),
      'glazing' => array('Glass•LoĒ³', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
    ),
    'doors/french-swing-doors/zenith' => array(
      'name' => 'Zenith French Swing Door',
      'series' => 'zenith',
      'style' => 'french-swing',
      'legacy' => '/products/french-swing-doors/zenith-french-swing-door/',
      'lead' => 'French swing doors feature 1 or 2 panels that swing outward or inward and from the left or right.',
      'views' => array(
        array('Standard', '2024/09/PRM_Web-Zenith-Hero_0020_ZE_UNIT-SW.png'),
        array('Blinds outside', '2024/09/PRM_Web-Zenith-Hero_0021_ZE_UNIT-SW-ODL.png'),
        array('Blinds inside', '2024/09/PRM_Web-Zenith-Hero_0022_ZE_UNIT-SW-ODL-IN.png'),
        array('Operator', '2024/09/PRM_Web-Zenith-Hero_0023_ZE_UNIT-SW-ODL-IN-IG.png'),
      ),
      'highlights' => array('Elevated Luxury Experience', 'Cutting-Edge Performance Vinyl', 'Versatile Style Integration'),
      'material' => 'Performance Vinyl',
      'exterior' => array('Black'),
      'interior' => array('Black'),
      'blinds' => true,
      'benefits' => array(
        'title' => 'Performance Vinyl Benefits',
        'text' => 'Our innovative formula and performance co-extruded frames maintain the perfect balance between your desired luxury look and durability in the hottest of climates.',
        'items' => array('200°F Heat Resistance', 'Anti-Warping', 'Anti-Shrinking', 'Color-Fade Resistance'),
      ),
      'features' => array('Capstock Protection', 'Thin & Thick Sashes', 'Standard Hardware', 'Key Lock Standard', 'Even Sightlines'),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Streamlined Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
    ),
    'doors/french-swing-doors/serene' => array(
      'name' => 'Serene French Swing Door',
      'series' => 'serene',
      'style' => 'french-swing',
      'legacy' => '/products/french-swing-doors/serene-series-french-swing-door/',
      'lead' => 'French swing doors feature 1 or 2 panels that swing outward or inward and from the left or right.',
      'views' => array(array('', '2020/04/Thumb-Doors-French-Swing-Serene.jpg')),
      'highlights' => array('Sound Reduction', 'Energy Efficiency', 'Even Sightlines', 'Design Versatility'),
      'material' => 'Vinyl',
      'exterior' => array('White', 'Almond', 'Black Laminated'),
      'interior' => array('White', 'Almond'),
      'blinds' => true,
      'features' => array('Thick Door Sash', 'Standard Hardware', 'Key Lock Standard', 'Even Sightlines'),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
    ),
    'doors/french-swing-doors/elegance' => array(
      'name' => 'Elegance French Swing Door',
      'series' => 'elegance',
      'style' => 'french-swing',
      'legacy' => '/products/french-swing-doors/infinite-series-french-swing-door/',
      'lead' => 'French swing doors feature 1 or 2 panels that swing outward or inward and from the left or right.',
      'views' => array(array('', '2020/04/Thumb-Doors-French-Swing-Infinite.jpg')),
      'highlights' => array('Classic Styling', 'Even SightLines', 'Premium Durability'),
      'material' => 'Vinyl',
      'exterior' => array('White'),
      'interior' => array('White'),
      'blinds' => false,
      'features' => array('Thick Door Sash', 'Standard Hardware', 'Key Lock Standard', 'Even Sightlines'),
      'glazing' => array('Dual Pane', 'Dura Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
    ),
    'doors/french-swing-doors/aluminum' => array(
      'name' => 'Aluminum French Swing Door',
      'series' => 'aluminum',
      'style' => 'french-swing',
      'legacy' => '/products/french-swing-doors/aluminum-french-swing-door/',
      'lead' => 'French swing doors feature 1 or 2 panels that swing outward or inward and from the left or right.',
      'views' => array(array('', '2020/05/French-Swing-Aluminum-Doors.jpg')),
      'highlights' => array('Slim Sightlines', 'Thermal Superiority', 'Modern Aesthetic'),
      'material' => 'Aluminum',
      'exterior' => array('Clear Anodized', 'Bronze Anodized'),
      'interior' => array('Clear Anodized', 'Bronze Anodized'),
      'blinds' => false,
      'features' => array(
        '20 mil Anodized Protection',
        'Slim Door Sash',
        'Enhanced Hardware',
        'Key Lock Standard',
        'Even Sightlines',
      ),
      'glazing' => array('Glass•LoĒ³', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
    ),
    'doors/multiple-sliding-doors/serene' => array(
      'name' => 'Serene Multiple Sliding Door',
      'series' => 'serene',
      'style' => 'multi-slide',
      'legacy' => '/products/multiple-sliding-doors/serene-series-multiple-sliding-door/',
      'lead' => 'Multiple sliding doors allow for larger panoramic views and openings.',
      'views' => array(array('', '2020/04/Operation-Doors-Multiple-Sliding.jpg')),
      'highlights' => array('Sound Reduction', 'Energy Efficiency', 'Even Sightlines', 'Design Versatility'),
      'material' => 'Vinyl',
      'exterior' => array('White', 'Almond', 'Black Laminated'),
      'interior' => array('White', 'Almond'),
      'blinds' => true,
      'features' => array('Thick Door Sash', 'Standard Hardware', 'Key Lock Option Available', 'Even Sightlines'),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
    ),
    'doors/multiple-sliding-doors/aluminum' => array(
      'name' => 'Aluminum Multiple Sliding Door',
      'series' => 'aluminum',
      'style' => 'multi-slide',
      'legacy' => '/products/multiple-sliding-doors/aluminum-multiple-sliding-door/',
      'lead' => 'Multiple sliding doors allow for larger panoramic views and openings.',
      'views' => array(array('', '2020/05/Multiple-Sliding-Aluminum-Doors.jpg')),
      'highlights' => array('Slim Sightlines', 'Thermal Superiority', 'Modern Aesthetic'),
      'material' => 'Aluminum',
      'exterior' => array('Clear Anodized', 'Bronze Anodized'),
      'interior' => array('Clear Anodized', 'Bronze Anodized'),
      'blinds' => false,
      'features' => array(
        '20 mil Anodized Protection',
        'Slim Door Sash',
        'Enhanced Hardware',
        'Key Lock Option Available',
        'Even Sightlines',
      ),
      'glazing' => array('Glass•LoĒ³', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
    ),
    'doors/multiple-folding-doors/serene' => array(
      'name' => 'Serene Multiple Folding Door',
      'series' => 'serene',
      'style' => 'multi-fold',
      'legacy' => '/products/multiple-folding-doors/serene-series-multiple-folding-door/',
      'lead' => 'Multiple folding doors feature two or more folding panels and create maximum outdoor connection when fully opened.',
      'views' => array(array('', '2020/04/Thumb-Doors-Multiple-Folding-Serene.jpg')),
      'highlights' => array('Sound Reduction', 'Energy Efficiency', 'Even Sightlines', 'Design Versatility'),
      'material' => 'Vinyl',
      'exterior' => array('White', 'Almond', 'Black Laminated'),
      'interior' => array('White', 'Almond'),
      'blinds' => true,
      'features' => array('Thick Door Sash', 'Standard Hardware', 'Key Lock Standard', 'Even Sightlines'),
      'glazing' => array('Dual Pane', 'Dura Pane', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
    ),
    'doors/multiple-folding-doors/aluminum' => array(
      'name' => 'Aluminum Multiple Folding Door',
      'series' => 'aluminum',
      'style' => 'multi-fold',
      'legacy' => '/products/multiple-folding-doors/aluminum-multiple-folding-door/',
      'lead' => 'Multiple folding doors feature two or more folding panels and create maximum outdoor connection when fully opened.',
      'views' => array(array('', '2020/05/Multiple-Folding-Aluminum-Doors.jpg')),
      'highlights' => array('Slim Sightlines', 'Thermal Superiority', 'Modern Aesthetic'),
      'material' => 'Aluminum',
      'exterior' => array('Clear Anodized', 'Bronze Anodized'),
      'interior' => array('Clear Anodized', 'Bronze Anodized'),
      'blinds' => false,
      'features' => array(
        '20 mil Anodized Protection',
        'Slim Door Sash',
        'Enhanced Hardware',
        'Key Lock Standard',
        'Even Sightlines',
      ),
      'glazing' => array('Glass•LoĒ³', 'Triple Pane'),
      'specs' => array(
        'Grids' => 'Grids Between Glass Only',
        'Glass Textures' => 'Glazing Option Dependent',
        'Spacers' => 'Duraseal® Warm-Edge Spacer',
        'Insulation' => 'Argon Gas Insulation',
        'Framing' => 'Configuration Dependent Reinforcements • Standard Weep Covers',
        'Certifications' => 'ASTM • NFRC • AAMA',
      ),
    ),
  );
}

// Bloque de cierre de cada serie, por tipo de producto (serie-window / serie-door).
function pwd_product_series_copy() {
  return array(
    'elegance-window' => array(
      'lead' => 'Rooted in tradition, refined for the present',
      'text' => 'Made for projects that demand more than just function, this series was designed for those who value the rich details of traditional architecture and believe that compromise isn’t an option. Whether you’re restoring a historic residence or adhering to HOA requirements in a heritage neighborhood, the Elegance Series™ Windows & Doors are built to preserve the past while performing for the future.',
      'image' => '2025/06/PRM-Series-Summary-Elegance-Windows.jpg',
    ),
    'timeless-window' => array(
      'lead' => 'Our best-selling vinyl series that stands the test of time',
      'text' => 'With its streamlined aesthetic, superior craftsmanship, and competitive pricing, the Timeless Series™ is the go-to solution for most window and door needs. Its versatility extends to both replacement and new construction projects, offering dependable performance in a wide range of applications. By focusing on core essentials including durability, larger views, and low maintenance, the Timeless Series maximizes value without compromising on quality, making it a smart, easy choice for homeowners and professionals alike.',
      'image' => '2026/09/VIZ-Timeless-Home-Basic-Back.jpg',
    ),
    'aluminum-window' => array(
      'lead' => 'Experience the highest luxury and energy performance.',
      'text' => 'With exceptional engineering and meticulously selected top of the line components, Aluminum Series offers excellent options that will bring an elegant look and comfort to your home for many years to come. Take a closer look at our Aluminum Series features and benefits for your replacement or new construction project.',
      'image' => '2025/06/PRM-Series-Summary-Aluminum-Windows.jpg',
    ),
    'serene-window' => array(
      'lead' => 'Tranquility, efficiency, and versatility for any project',
      'text' => 'Designed for luxury homes where quality, versatility, and peace matter, the Serene Series™ a comprehensive range of design options and advanced glazing techniques meeting the demands of tasteful homeowners who want nothing less than the very best.',
      'image' => '2025/06/PRM-Series-Summary-Serene-Windows.jpg',
    ),
    'zenith-window' => array(
      'lead' => 'Achieve your dream vision with the luxury design of the Zenith Series Windows & Doors.',
      'text' => 'Advanced materials and cutting-edge technology deliver exceptional performance and durability. Superior heat resistance, fade-resistant color formula, top-tier sound insulation, and the highest energy efficiency standards overcome climate limitations of traditional vinyl windows. The style and strength of the Zenith Series provide a new level of high-end design opportunities for residential and commercial projects. Achieve your dream vision of luxury design.',
      'image' => '2025/06/PRM-Series-Summary-Zenith-Windows.jpg',
    ),
    'aluminum-door' => array(
      'lead' => 'Experience the highest luxury and energy performance.',
      'text' => 'With exceptional engineering and meticulously selected top of the line components, Aluminum Series offers excellent options that will bring an elegant look and comfort to your home for many years to come. Take a closer look at our Aluminum Series features and benefits for your replacement or new construction project.',
      'image' => '2025/06/PRM-Series-Summary-Aluminum-Doors.jpg',
    ),
    'elegance-door' => array(
      'lead' => 'Rooted in tradition, refined for the present',
      'text' => 'Made for projects that demand more than just function, this series was designed for those who value the rich details of traditional architecture and believe that compromise isn’t an option. Whether you’re restoring a historic residence or adhering to HOA requirements in a heritage neighborhood, the Elegance Series™ Windows & Doors are built to preserve the past while performing for the future.',
      'image' => '2025/06/PRM-Series-Summary-Elegance-Doors.jpg',
    ),
    'serene-door' => array(
      'lead' => 'Tranquility, efficiency, and versatility for any project',
      'text' => 'Designed for luxury homes where quality, versatility, and peace matter, the Serene Series™ a comprehensive range of design options and advanced glazing techniques meeting the demands of tasteful homeowners who want nothing less than the very best.',
      'image' => '2025/06/PRM-Series-Summary-Serene-Doors.jpg',
    ),
    'zenith-door' => array(
      'lead' => 'Achieve your dream vision with the luxury design of the Zenith Series Windows & Doors.',
      'text' => 'Advanced materials and cutting-edge technology deliver exceptional performance and durability. Superior heat resistance, fade-resistant color formula, top-tier sound insulation, and the highest energy efficiency standards overcome climate limitations of traditional vinyl windows. The style and strength of the Zenith Series provide a new level of high-end design opportunities for residential and commercial projects. Achieve your dream vision of luxury design.',
      'image' => '2025/06/PRM-Series-Summary-Zenith-Doors.jpg',
    ),
    'timeless-door' => array(
      'lead' => 'Our best-selling vinyl series that stands the test of time',
      'text' => 'With its streamlined aesthetic, superior craftsmanship, and competitive pricing, the Timeless Series™ is the go-to solution for most window and door needs. Its versatility extends to both replacement and new construction projects, offering dependable performance in a wide range of applications. By focusing on core essentials including durability, larger views, and low maintenance, the Timeless Series maximizes value without compromising on quality, making it a smart, easy choice for homeowners and professionals alike.',
      'image' => '2026/09/VIZ-PetDoor-Timeless-Exterior-Back-Yard.jpg',
    ),
  );
}
