<?php
// Inventario de PDFs de las fichas del sitio actual (premiumwindows.com, revisado 2026-10-03).
// Clave: ruta en uploads (se conserva para que las URLs públicas no cambien).
// Títulos normalizados. Correcciones respecto al sitio actual:
//   2025/07/TI-SL-XOO-N1-250715.pdf: enlazado en products/patio-sliding-doors/zenith-patio-sliding-door/; se asigna solo a Timeless
//   2024/10/ZE-SHOSH_PW-N1-250715.pdf: "Retrofit 1″" corregido a "Nail-On 1″"
//   2024/10/ZE-SHOSH_PW-N13-250715.pdf: "Retrofit 1-3/8″" corregido a "Nail-On 1-3/8″"
//   2024/10/ZE-SLT-OXO-BK-250715.pdf: 2 etiquetas distintas en el sitio actual → "Zenith Patio Door OXO Block Frame (Traditional)"
//   2024/10/ZE-SLT-OXO-N1-250715.pdf: 2 etiquetas distintas en el sitio actual → "Zenith Patio Door OXO Nail-On 1″ Frame (Traditional)"
//   2024/10/ZE-SLT-OXO-N13-250715.pdf: 2 etiquetas distintas en el sitio actual → "Zenith Patio Door OXO Nail-On 1-3/8″ Frame (Traditional)"
//   2024/10/ZE-SLT-OXO-R2-250715.pdf: 2 etiquetas distintas en el sitio actual → "Zenith Patio Door OXO Retrofit 2-1/2″ Frame (Traditional)"
//   2024/10/ZE-SLT-OXXO-BK-250715.pdf: 2 etiquetas distintas en el sitio actual → "Zenith Patio Door OXXO Block Frame (Traditional)"
//   2024/10/ZE-SLT-XOO-N13-250715.pdf: 2 etiquetas distintas en el sitio actual → "Zenith Patio Door XOO Nail-On 1-3/8″ Frame (Traditional)"
//   2025/07/TI-SL-XOO-N1-250715.pdf: 2 etiquetas distintas en el sitio actual → "Timeless Patio Door XOO Nail-On 1″ Frame"
// Lo usa `wp pwd import-product-docs` para crear los adjuntos y asignar las taxonomías de pwd_document_taxonomies().
function pwd_product_documents() {
  return array(
    '2020/03/TI-XO-BK-250715.pdf' => array(
      'title' => 'Timeless Horizontal Slider Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2020/03/TI-XO-N1-250715.pdf' => array(
      'title' => 'Timeless Horizontal Slider Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2020/03/TI-XO-N13-250715.pdf' => array(
      'title' => 'Timeless Horizontal Slider Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2020/03/TI-XO-R1-250715.pdf' => array(
      'title' => 'Timeless Horizontal Slider Retrofit 1-3/4″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Retrofit 1-3/4″',
    ),
    '2020/03/TI-XO-R2-250715.pdf' => array(
      'title' => 'Timeless Horizontal Slider Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2020/03/TI-XOX_PW-BK-250715.pdf' => array(
      'title' => 'Timeless XOX PW Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2020/03/TI-XOX_PW-N1-250715.pdf' => array(
      'title' => 'Timeless XOX PW Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2020/03/TI-XOX_PW-N13-250715.pdf' => array(
      'title' => 'Timeless XOX PW Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2020/03/TI-XOX_PW-R1-250715.pdf' => array(
      'title' => 'Timeless XOX PW Retrofit 1-3/4″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Retrofit 1-3/4″',
    ),
    '2020/03/TI-XOX_PW-R2-250715.pdf' => array(
      'title' => 'Timeless XOX PW Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2020/05/TI-SH-BK-250715.pdf' => array(
      'title' => 'Timeless Single Hung Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2020/05/TI-SH-N1-250715.pdf' => array(
      'title' => 'Timeless Single Hung Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2020/05/TI-SH-N13-250715.pdf' => array(
      'title' => 'Timeless Single Hung Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2020/05/TI-SH-R1-250715.pdf' => array(
      'title' => 'Timeless Single Hung Retrofit 1-3/4″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Retrofit 1-3/4″',
    ),
    '2020/05/TI-SH-R2-250715.pdf' => array(
      'title' => 'Timeless Single Hung Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2020/05/TI-SHOSH_PW-BK-250715.pdf' => array(
      'title' => 'Timeless SHOSH PW Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2020/05/TI-SHOSH_PW-N1-250715.pdf' => array(
      'title' => 'Timeless SHOSH PW Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2020/05/TI-SHOSH_PW-N13-250715.pdf' => array(
      'title' => 'Timeless SHOSH PW Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2020/05/TI-SHOSH_PW-R1-250715.pdf' => array(
      'title' => 'Timeless SHOSH PW Retrofit 1-3/4″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Retrofit 1-3/4″',
    ),
    '2020/05/TI-SHOSH_PW-R2-250715.pdf' => array(
      'title' => 'Timeless SHOSH PW Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2021/10/Casement-and-Awning-window-installation-complete-guide_compressed.pdf' => array(
      'title' => 'Casement & Awning Window Installation Guide',
      'type' => 'Installation Guide',
      'series' => array('aluminum', 'serene', 'zenith'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => null,
    ),
    '2021/10/Fixed-Picture-window-installation-complete-guide_reduced-file-size.pdf' => array(
      'title' => 'Fixed Picture Window Installation Guide',
      'type' => 'Installation Guide',
      'series' => array('elegance', 'timeless', 'aluminum', 'serene', 'zenith'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => null,
    ),
    '2021/10/French-Swing-Door-installation-complete-guide_compressed.pdf' => array(
      'title' => 'French Swing Door Installation Guide',
      'type' => 'Installation Guide',
      'series' => array('aluminum', 'elegance', 'serene', 'zenith'),
      'styles' => array('french-swing'),
      'products' => array('door'),
      'frame' => null,
    ),
    '2021/10/Horizontal-Sliding-window-installation-complete-guide-compressed.pdf' => array(
      'title' => 'Horizontal Sliding Window Installation Guide',
      'type' => 'Installation Guide',
      'series' => array('aluminum', 'elegance', 'serene', 'timeless', 'zenith'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => null,
    ),
    '2021/10/Single-Hung-tilt-window-installation-complete-guide-compressed.pdf' => array(
      'title' => 'Single Hung Tilt Window Installation Guide',
      'type' => 'Installation Guide',
      'series' => array('aluminum', 'elegance', 'serene', 'timeless', 'zenith'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => null,
    ),
    '2024/10/ZE-CM-BK-250715.pdf' => array(
      'title' => 'Zenith Casement Window Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-CM-N1-250715.pdf' => array(
      'title' => 'Zenith Casement Window Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-CM-N13-250715.pdf' => array(
      'title' => 'Zenith Casement Window Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-CM-R2-250715.pdf' => array(
      'title' => 'Zenith Casement Window Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2024/10/ZE-CM2X-BK-250715.pdf' => array(
      'title' => 'Zenith Double Casement Window Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-CM2X-N1-250715.pdf' => array(
      'title' => 'Zenith Double Casement Window Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-CM2X-N13-250715.pdf' => array(
      'title' => 'Zenith Double Casement Window Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-CM2X-R2-250715.pdf' => array(
      'title' => 'Zenith Double Casement Window Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2024/10/ZE-DH-BK-250715.pdf' => array(
      'title' => 'Zenith Double Hung Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('double-hung'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-DH-N1-250715.pdf' => array(
      'title' => 'Zenith Double Hung Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('double-hung'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-DH-N13-250715.pdf' => array(
      'title' => 'Zenith Double Hung Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('double-hung'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-DH-R2-250715.pdf' => array(
      'title' => 'Zenith Double Hung Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('double-hung'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2024/10/ZE-PW-BK-250715.pdf' => array(
      'title' => 'Zenith Picture Window Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('picture'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-PW-N1-250715.pdf' => array(
      'title' => 'Zenith Picture Window Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('picture'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-PW-N13-250715.pdf' => array(
      'title' => 'Zenith Picture Window Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('picture'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-PW-R2-250715.pdf' => array(
      'title' => 'Zenith Picture Window Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('picture'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2024/10/ZE-PW2V-BK-250715.pdf' => array(
      'title' => 'Zenith Picture Window 2V Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('picture'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-PW2V-N1-250715.pdf' => array(
      'title' => 'Zenith Picture Window 2V Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('picture'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-PW2V-N13-250715.pdf' => array(
      'title' => 'Zenith Picture Window 2V Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('picture'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-PW2V-R2-250715.pdf' => array(
      'title' => 'Zenith Picture Window 2V Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('picture'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2024/10/ZE-SH-BK-250715.pdf' => array(
      'title' => 'Zenith Single Hung Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-SH-N1-250715.pdf' => array(
      'title' => 'Zenith Single Hung Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-SH-N13-250715.pdf' => array(
      'title' => 'Zenith Single Hung Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-SH-R2-250715.pdf' => array(
      'title' => 'Zenith Single Hung Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2024/10/ZE-SHOSH_PW-BK-250715.pdf' => array(
      'title' => 'Zenith SHOSH PW Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-SHOSH_PW-N1-250715.pdf' => array(
      'title' => 'Zenith SHOSH PW Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-SHOSH_PW-N13-250715.pdf' => array(
      'title' => 'Zenith SHOSH PW Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-SHOSH_PW-R2-250715.pdf' => array(
      'title' => 'Zenith SHOSH PW Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2024/10/ZE-SL-OXXO-N1-250715.pdf' => array(
      'title' => 'Zenith Patio Door OXXO Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-SL-OXXO-N13-250715.pdf' => array(
      'title' => 'Zenith Patio Door OXXO Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-SL-OXXO-R2-250715.pdf' => array(
      'title' => 'Zenith Patio Door OXXO Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2024/10/ZE-SL-XO-BK-250715.pdf' => array(
      'title' => 'Zenith Patio Door XO Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-SL-XO-N1-250715.pdf' => array(
      'title' => 'Zenith Patio Door XO Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-SL-XO-N13-250715.pdf' => array(
      'title' => 'Zenith Patio Door XO Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-SL-XO-R2-250715.pdf' => array(
      'title' => 'Zenith Patio Door XO Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2024/10/ZE-SL-XOO-BK-250715.pdf' => array(
      'title' => 'Zenith Patio Door XOO Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-SL-XOO-N13-250715.pdf' => array(
      'title' => 'Zenith Patio Door XOO Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-SL-XOO-R2-250715.pdf' => array(
      'title' => 'Zenith Patio Door XOO Retrofit 2-3/4″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Retrofit 2-3/4″',
    ),
    '2024/10/ZE-SLT-OXO-BK-250715.pdf' => array(
      'title' => 'Zenith Patio Door OXO Block Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-SLT-OXO-N1-250715.pdf' => array(
      'title' => 'Zenith Patio Door OXO Nail-On 1″ Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-SLT-OXO-N13-250715.pdf' => array(
      'title' => 'Zenith Patio Door OXO Nail-On 1-3/8″ Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-SLT-OXO-R2-250715.pdf' => array(
      'title' => 'Zenith Patio Door OXO Retrofit 2-1/2″ Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2024/10/ZE-SLT-OXXO-BK-250715.pdf' => array(
      'title' => 'Zenith Patio Door OXXO Block Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-SLT-OXXO-N1-250715.pdf' => array(
      'title' => 'Zenith Patio Door OXXO Nail-On 1″ Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-SLT-OXXO-R2-250715.pdf' => array(
      'title' => 'Zenith Patio Door OXXO Retrofit 2-1/2″ Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2024/10/ZE-SLT-XO-BK-250715.pdf' => array(
      'title' => 'Zenith Patio Door XO Block Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-SLT-XO-N1-250715.pdf' => array(
      'title' => 'Zenith Patio Door XO Nail-On 1″ Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-SLT-XO-N13-250715.pdf' => array(
      'title' => 'Zenith Patio Door XO Nail-On 1-3/8″ Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-SLT-XO-R2-250715.pdf' => array(
      'title' => 'Zenith Patio Door XO Retrofit 2-1/2″ Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2024/10/ZE-SLT-XOO-BK-250715.pdf' => array(
      'title' => 'Zenith Patio Door XOO Block Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-SLT-XOO-N1-250715.pdf' => array(
      'title' => 'Zenith Patio Door XOO Nail-On 1″ Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-SLT-XOO-N13-250715.pdf' => array(
      'title' => 'Zenith Patio Door XOO Nail-On 1-3/8″ Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-SLT-XOO-R2-250715.pdf' => array(
      'title' => 'Zenith Patio Door XOO Retrofit 2-3/4″ Frame (Traditional)',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Retrofit 2-3/4″',
    ),
    '2024/10/ZE-XO-BK-250715.pdf' => array(
      'title' => 'Zenith Horizontal Slider Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-XO-N1-250715.pdf' => array(
      'title' => 'Zenith Horizontal Slider Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-XO-N13-250715.pdf' => array(
      'title' => 'Zenith Horizontal Slider Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-XO-R2-250715.pdf' => array(
      'title' => 'Zenith Horizontal Slider Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2024/10/ZE-XOX_PW-BK-250715.pdf' => array(
      'title' => 'Zenith XOX PW Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2024/10/ZE-XOX_PW-N1-250715.pdf' => array(
      'title' => 'Zenith XOX PW Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2024/10/ZE-XOX_PW-N13-250715.pdf' => array(
      'title' => 'Zenith XOX PW Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2024/10/ZE-XOX_PW-R2-250715.pdf' => array(
      'title' => 'Zenith XOX PW Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('zenith'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2025/07/SE-CM-BK-250715-b.pdf' => array(
      'title' => 'Serene Casement Window Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('serene'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2025/07/SE-CM-N1-250715-b.pdf' => array(
      'title' => 'Serene Casement Window Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('serene'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2025/07/SE-CM-N13-250715-b.pdf' => array(
      'title' => 'Serene Casement Window Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('serene'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2025/07/SE-CM-R1-250715-b.pdf' => array(
      'title' => 'Serene Casement Window Retrofit 1-3/4″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('serene'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Retrofit 1-3/4″',
    ),
    '2025/07/SE-CM2V-BK-250715-b.pdf' => array(
      'title' => 'Serene Double Casement Window Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('serene'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2025/07/SE-CM2V-N1-250715-b.pdf' => array(
      'title' => 'Serene Double Casement Window Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('serene'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2025/07/SE-CM2V-N13-250715-b.pdf' => array(
      'title' => 'Serene Double Casement Window Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('serene'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2025/07/SE-CM2V-R1-250715-b.pdf' => array(
      'title' => 'Serene Double Casement Window Retrofit 1-3/4″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('serene'),
      'styles' => array('casement-awning'),
      'products' => array('window'),
      'frame' => 'Retrofit 1-3/4″',
    ),
    '2025/07/TI-PW-BK-250715.pdf' => array(
      'title' => 'Timeless Picture Window Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2025/07/TI-PW-N1-250715.pdf' => array(
      'title' => 'Timeless Picture Window Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2025/07/TI-PW-N13-250715.pdf' => array(
      'title' => 'Timeless Picture Window Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2025/07/TI-PW-R1-250715.pdf' => array(
      'title' => 'Timeless Picture Window Retrofit 1-3/4″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => 'Retrofit 1-3/4″',
    ),
    '2025/07/TI-PW-R2-250715.pdf' => array(
      'title' => 'Timeless Picture Window Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2025/07/TI-PW2V-BK-250715.pdf' => array(
      'title' => 'Timeless Picture Window 2V Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2025/07/TI-PW2V-N1-250715.pdf' => array(
      'title' => 'Timeless Picture Window 2V Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2025/07/TI-PW2V-N13-250715.pdf' => array(
      'title' => 'Timeless Picture Window 2V Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2025/07/TI-PW2V-R1-250715.pdf' => array(
      'title' => 'Timeless Picture Window 2V Retrofit 1-3/4″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => 'Retrofit 1-3/4″',
    ),
    '2025/07/TI-PW2V-R2-250715.pdf' => array(
      'title' => 'Timeless Picture Window 2V Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2025/07/TI-SL-OXO-BK-250715.pdf' => array(
      'title' => 'Timeless Patio Door OXO Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Block',
    ),
    '2025/07/TI-SL-OXO-N1-250715.pdf' => array(
      'title' => 'Timeless Patio Door OXO Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1″',
    ),
    '2025/07/TI-SL-OXO-N13-250715.pdf' => array(
      'title' => 'Timeless Patio Door OXO Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2025/07/TI-SL-OXO-R2-250715.pdf' => array(
      'title' => 'Timeless Patio Door OXO Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2025/07/TI-SL-OXXO-BK-250715.pdf' => array(
      'title' => 'Timeless Patio Door OXXO Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Block',
    ),
    '2025/07/TI-SL-OXXO-N1-250715.pdf' => array(
      'title' => 'Timeless Patio Door OXXO Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1″',
    ),
    '2025/07/TI-SL-OXXO-N13-250715.pdf' => array(
      'title' => 'Timeless Patio Door OXXO Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2025/07/TI-SL-OXXO-R2-250715.pdf' => array(
      'title' => 'Timeless Patio Door OXXO Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2025/07/TI-SL-XO-BK-250715.pdf' => array(
      'title' => 'Timeless Patio Door XO Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Block',
    ),
    '2025/07/TI-SL-XO-N1-250715.pdf' => array(
      'title' => 'Timeless Patio Door XO Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1″',
    ),
    '2025/07/TI-SL-XO-N13-250715.pdf' => array(
      'title' => 'Timeless Patio Door XO Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2025/07/TI-SL-XO-R2-250715.pdf' => array(
      'title' => 'Timeless Patio Door XO Retrofit 2-3/4″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Retrofit 2-3/4″',
    ),
    '2025/07/TI-SL-XOO-BK-250715.pdf' => array(
      'title' => 'Timeless Patio Door XOO Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Block',
    ),
    '2025/07/TI-SL-XOO-N1-250715.pdf' => array(
      'title' => 'Timeless Patio Door XOO Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1″',
    ),
    '2025/07/TI-SL-XOO-N13-250715.pdf' => array(
      'title' => 'Timeless Patio Door XOO Nail-On 1-3/8″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Nail-On 1-3/8″',
    ),
    '2025/07/TI-SL-XOO-R2-250715.pdf' => array(
      'title' => 'Timeless Patio Door XOO Retrofit 2-1/2″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('timeless'),
      'styles' => array('patio-sliding'),
      'products' => array('door'),
      'frame' => 'Retrofit 2-1/2″',
    ),
    '2026/01/EL-PW-BK-251220.pdf' => array(
      'title' => 'Elegance Picture Window Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('elegance'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2026/01/EL-PW-N1-251220.pdf' => array(
      'title' => 'Elegance Picture Window Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('elegance'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2026/01/EL-PW-R1-251220.pdf' => array(
      'title' => 'Elegance Picture Window Retrofit 1-3/4″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('elegance'),
      'styles' => array('arch-special-shape', 'picture'),
      'products' => array('window'),
      'frame' => 'Retrofit 1-3/4″',
    ),
    '2026/01/EL-SH-BK-251220.pdf' => array(
      'title' => 'Elegance Single Hung Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('elegance'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2026/01/EL-SH-N1-251220.pdf' => array(
      'title' => 'Elegance Single Hung Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('elegance'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2026/01/EL-SH-R1-251220.pdf' => array(
      'title' => 'Elegance Single Hung Retrofit 1-3/4″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('elegance'),
      'styles' => array('single-hung'),
      'products' => array('window'),
      'frame' => 'Retrofit 1-3/4″',
    ),
    '2026/01/EL-XO-BK-251220.pdf' => array(
      'title' => 'Elegance Horizontal Slider Block Frame',
      'type' => 'Detail Drawing',
      'series' => array('elegance'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Block',
    ),
    '2026/01/EL-XO-N1-251220.pdf' => array(
      'title' => 'Elegance Horizontal Slider Nail-On 1″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('elegance'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Nail-On 1″',
    ),
    '2026/01/EL-XO-R1-251220.pdf' => array(
      'title' => 'Elegance Horizontal Slider Retrofit 1-3/4″ Frame',
      'type' => 'Detail Drawing',
      'series' => array('elegance'),
      'styles' => array('horizontal-sliding'),
      'products' => array('window'),
      'frame' => 'Retrofit 1-3/4″',
    ),
  );
}
